### ISSUE TITLE
GitHub Actions support

### ISSUE THREAD

**Issue by nathany** [radditude/coveralls-multi#10]
Thanks for the gem. 

Is it possible to write out the merged file without posting to Travis CI? Then it could be picked up by https://github.com/coverallsapp/github-action.

**Comment by nathany** [comment]
Like #5, this seems like more of a documentation problem.

I see `COVERALLS_RUN_LOCALLY` at https://github.com/radditude/coveralls-multi/blob/main/lib/coveralls-multi/config.rb#L92.

So I'm trying something like this:

```
# Coveralls Multi config https://github.com/radditude/coveralls-multi
service_name: manual
multi:
  lcov: assets/coverage/lcov.info
  excoveralls: cover/excoveralls.json
debug_mode: true
```

And running `COVERALLS_RUN_LOCALLY=true coveralls-multi`

But I still see the same error as when I hadn't added those things.

```
[CoverallsMulti] Couldn't find a repository matching this job.
[CoverallsMulti] Error: true
```

What am I missing? Thanks!
